version: '3.8'

services:
  fake-news-detection:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
